name: onegate
description: "A secure note-taking app with dual-layer encryption."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  supabase_flutter: ^2.0.0
  uuid: ^4.2.2
  path_provider: ^2.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
